"""add party_name to sales

Revision ID: 26296569f716
Revises: fde3a9e477ae
Create Date: 2026-04-21 15:39:18.661957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26296569f716'
down_revision = 'fde3a9e477ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_user_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_batches_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_po_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_batches_user_id'))

    op.drop_table('inventory_batches')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))
        batch_op.drop_index(batch_op.f('ix_suppliers_user_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_po_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_product_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('batch_consumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_batch_id'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_stock_movement_id'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_user_id'))

    op.drop_table('batch_consumptions')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('party_name')

    op.create_table('batch_consumptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_movement_id', sa.INTEGER(), nullable=False),
    sa.Column('batch_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_consumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_consumptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_stock_movement_id'), ['stock_movement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_batch_id'), ['batch_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('po_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('batch_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_po_id'), ['po_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('email', sa.VARCHAR(length=160), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)

    op.create_table('inventory_batches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('po_item_id', sa.INTEGER(), nullable=True),
    sa.Column('batch_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('quantity_received', sa.INTEGER(), nullable=False),
    sa.Column('quantity_remaining', sa.INTEGER(), nullable=False),
    sa.Column('received_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_batches_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_po_item_id'), ['po_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_batches_created_at'), ['created_at'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=24), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=True),
    sa.Column('received_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
