"""add gst to sales

Revision ID: 2d500fd6de2d
Revises: 26296569f716
Create Date: 2026-04-21 15:52:54.741012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d500fd6de2d'
down_revision = '26296569f716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('gst_rate')

    # ### end Alembic commands ###
