"""add batch consumption

Revision ID: fde3a9e477ae
Revises: 38c86ac28141
Create Date: 2026-03-16 15:15:13.187052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde3a9e477ae'
down_revision = '38c86ac28141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_consumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_consumptions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_stock_movement_id'), ['stock_movement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_consumptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_consumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_stock_movement_id'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_batch_consumptions_batch_id'))

    op.drop_table('batch_consumptions')
    # ### end Alembic commands ###
